INSERT INTO network(name) VALUES("Electricité");
INSERT INTO network(name) VALUES("Eau");
INSERT INTO network(name) VALUES("Bus");
INSERT INTO network(name) VALUES("Admin");
INSERT INTO type (name, network_id) VALUES ("Arrêt de bus",3);
INSERT INTO type (name, network_id) VALUES ("Dépôt de bus",3);
INSERT INTO type (name, network_id) VALUES ("Poteau haute tension",1);
INSERT INTO type (name, network_id) VALUES ("Central éléctrique",1);
INSERT INTO type (name, network_id) VALUES ("Fontaine",2);
INSERT INTO type (name, network_id) VALUES ("Château d'eau",2);
